# Generating MoTrPAC GMTs via DGE with DESeq2

This is the second step in the workflow
While the processed rnaseq files are sufficient to submit individually to the chea-kg-ts site, to reduce runtime of the example reports we will precompute the dges here

In [7]:
# general
import pandas as pd
import numpy as np
import json
import requests
import urllib
from IPython.display import display, FileLink, HTML, Markdown
import time
import os
import glob

# differential gene expression
from maayanlab_bioinformatics.dge import deseq2_differential_expression, characteristic_direction, up_down_from_characteristic_direction

import sys
import contextlib
@contextlib.contextmanager
def suppress_output(stdout=True, stderr=True, dest=os.devnull):
    ''' Usage:
    with suppress_output():
        print('hi')
    '''
    dev_null = open(dest, 'a')
    if stdout:
        _stdout = sys.stdout
        sys.stdout = dev_null
    if stderr:
        _stderr = sys.stderr
        sys.stderr = dev_null
    try:
        yield
    finally:
        if stdout:
            sys.stdout = _stdout
        if stderr:
            sys.stderr = _stderr

In [ ]:
def get_gene_lists(input_csv):
    """
    Outputs list of upregulated DEGs from DESeq2 results CSV.
    """
    df = pd.read_csv(input_csv)

    ## up genes ##
    filtered = df.loc[df["log2FoldChange"] > 0, df.columns[0]]
    up_gene_ids = list(filtered)

    up_list = []
    for up_gene in up_gene_ids:
        if "_" in up_gene:
            up_list.append(up_gene.split("_", 1)[1])
        else:
            up_list.append(up_gene)

    ## down genes ##
    filtered = df.loc[df["log2FoldChange"] < 0, df.columns[0]]
    dn_gene_ids = list(filtered)

    down_list = []
    for dn_gene in dn_gene_ids:
        if "_" in dn_gene:
            down_list.append(dn_gene.split("_", 1)[1])
        else:
            down_list.append(dn_gene)

    return up_list, down_list


def deseq2_csv_to_gmt(input_csv_list, comparisons, filename):
    """
    Converts list of csv files to two GMTs, comparing time vs 0 and time vs time
    """
    gmt_dict = {}
    trimmed_filenames = {x: x.replace("out/rat/dge/", "").replace("_deseq2","").split(".")[0].replace("_"," ") for x in input_csv_list}
    results_table = pd.DataFrame(index=trimmed_filenames.values(), columns=["up genes", "down genes"])

    for i, file in enumerate(input_csv_list):
        up_genes, down_genes = get_gene_lists(file)
        results_table.loc[trimmed_filenames[file], "up genes"] = len(up_genes)
        results_table.loc[trimmed_filenames[file], "down genes"] = len(down_genes)
        gmt_dict[f"{comparisons[i]} up genes"] = up_genes
        gmt_dict[f"{comparisons[i]} down genes"] = down_genes

    with open(filename, "w") as file:
        for s,t in gmt_dict.items():
            file.write(str(s) + "\t\t" + "\t".join(t) + "\n")

    results_table.index.name = "comparison"
    
    return filename, results_table

In [ ]:
def chea_kg_ts_dge(prefix, count_matrix, metadata):
    raw_counts = pd.read_csv(count_matrix)
    sample_metadata = pd.read_csv(metadata)

    assert sample_metadata['time_pt_annotation'].value_counts().min() >= 2, "Each time point must have at least two replicates"

    time_pt_list = [] 

    for time_pt in sample_metadata["time_pt_annotation"].tolist():
        if time_pt not in time_pt_list:
            time_pt_list.append(time_pt) 
    
    time_pt_dict = {} 
    for i, time_pt in enumerate(time_pt_list):
        samples_at_time_pt = sample_metadata.loc[sample_metadata["time_pt_annotation"] == time_pt, "sample_name"].astype(str).tolist()
        if raw_counts.columns[0] == "gene_id": # TODO: set raw count index to genes
            subset_counts = raw_counts[["gene_id"] + samples_at_time_pt]
            rev_subset_counts = subset_counts.set_index("gene_id")
            time_pt_dict[i] = (time_pt, rev_subset_counts)
        elif raw_counts.columns[0] == "gene_name":
            subset_counts = raw_counts[["gene_name"] + samples_at_time_pt]
            rev_subset_counts = subset_counts.set_index("gene_name")
            time_pt_dict[i] = (time_pt, rev_subset_counts)
    
    adj_time_pt_comparisons = []
    adj_time_pt_degs = []

    for i in range(len(time_pt_list) - 1):
        controls, cases = time_pt_dict[i][1], time_pt_dict[i+1][1]
        with suppress_output():
            results_df = deseq2_differential_expression(controls, cases)

        p_vals = [0.05] + [10**(-i) for i in range(2, 21, 1)]
        significant_genes = results_df[results_df["padj"] < p_vals[0]]
        up_count = (significant_genes["log2FoldChange"] > 0).sum()
        down_count = (significant_genes["log2FoldChange"] < 0).sum()

        idx = 1
        while (up_count + down_count) > 2000:
            significant_genes = results_df[results_df["padj"] < p_vals[idx]]
            up_count = (significant_genes["log2FoldChange"] > 0).sum()
            down_count = (significant_genes["log2FoldChange"] < 0).sum()
            idx += 1

        ctrl_time_pt, case_time_pt = time_pt_dict[i][0], time_pt_dict[i+1][0]
        adj_time_pt_comparisons.append(f"{ctrl_time_pt} v {case_time_pt}")

        file = f"out/rat/dge/{prefix}_deseq2_{case_time_pt}_v_{ctrl_time_pt}.csv"
        significant_genes.to_csv(file)
        adj_time_pt_degs.append(file)
    
    time_pt_0_comparisons = []
    time_pt_0_degs = [] 
    for i in range(1, len(time_pt_list)):
        controls, cases = time_pt_dict[0][1], time_pt_dict[i][1]
        with suppress_output():
            results_df = deseq2_differential_expression(controls, cases)

        p_vals = [0.05] + [10**(-i) for i in range(2, 21, 1)]
        significant_genes = results_df[results_df["padj"] < p_vals[0]]
        up_count = (significant_genes["log2FoldChange"] > 0).sum()
        down_count = (significant_genes["log2FoldChange"] < 0).sum() 

        idx = 1
        while (up_count + down_count) > 2000:
            significant_genes = results_df[results_df["padj"] < p_vals[idx]]
            up_count = (significant_genes["log2FoldChange"] > 0).sum()
            down_count = (significant_genes["log2FoldChange"] < 0).sum()
            idx += 1

        ctrl_time_pt, case_time_pt = time_pt_dict[0][0], time_pt_dict[i][0]
        time_pt_0_comparisons.append(f"{ctrl_time_pt} v {case_time_pt}")

        file = f"out/rat/dge/{prefix}_{case_time_pt}_v_{ctrl_time_pt}.csv"
        significant_genes.to_csv(file)
        time_pt_0_degs.append(file)
    
    display(Markdown("**Adjacent Time Point Comparisons**"))
    deseq2_degs_gmt_1, results_table1 = deseq2_csv_to_gmt(adj_time_pt_degs, adj_time_pt_comparisons, f"out/rat/gmts/motrpac_rat_{prefix}_adj_time_pt_degs.gmt")
    for file in adj_time_pt_degs:
        trimmed_filename = file.replace("results/deseq2_", "").split(".")[0].replace("_"," ")
    display(results_table1)

    display(Markdown("**Time Point Versus 0 Comparisons**"))
    deseq2_degs_gmt_2, results_table2 = deseq2_csv_to_gmt(time_pt_0_degs, time_pt_0_comparisons, f"out/rat/gmts/motrpac_rat_{prefix}_time_pt_0_degs.gmt")  
    for file in time_pt_0_degs:
        trimmed_filename = file.replace("results/deseq2_", "").split(".")[0].replace("_"," ")
    display(results_table2)

In [ ]:
all_results = dict()
for tissue in os.listdir("./out/rat/processed_rnaseq"):
    counts_matrix = f"./out/rat/processed_rnaseq/{tissue}/{tissue}_rna-seq_named.txt"
    
    M_prefix = f"{tissue}_male"
    male_metadata = f"./out/rat/processed_rnaseq/{tissue}/{tissue}_male_samples.csv"
    results = chea_kg_ts_dge(M_prefix, counts_matrix, male_metadata)
    all_results[M_prefix] = results

    F_prefix = f"{tissue}_female"
    female_metadata = f"./out/rat/processed_rnaseq/{tissue}/{tissue}_female_samples.csv"
    results = chea_kg_ts_dge(F_prefix, counts_matrix, female_metadata)
    all_results[F_prefix] = results

**Adjacent Time Point Comparisons**

                                        up genes down genes
comparison
blood-rna male male 1w v male sedentary      465        131
blood-rna male male 2w v male 1w               0          0
blood-rna male male 4w v male 2w             214        393
blood-rna male male 8w v male 4w            1024        361

**Time Point Versus 0 Comparisons**

                                        up genes down genes
comparison
blood-rna male male 1w v male sedentary      465        131
blood-rna male male 2w v male sedentary      697        462
blood-rna male male 4w v male sedentary        0          0
blood-rna male male 8w v male sedentary     1001        284

**Adjacent Time Point Comparisons**

                                              up genes down genes
comparison
blood-rna female female 1w v female sedentary       45         98
blood-rna female female 2w v female 1w               3          0
blood-rna female female 4w v female 2w               1          5
blood-rna female female 8w v female 4w              23          6

**Time Point Versus 0 Comparisons**

                                              up genes down genes
comparison
blood-rna female female 1w v female sedentary       45         98
blood-rna female female 2w v female sedentary        1          4
blood-rna female female 4w v female sedentary        0          0
blood-rna female female 8w v female sedentary        1          1

**Adjacent Time Point Comparisons**

                                     up genes down genes
comparison
cortex male male 1w v male sedentary        0          1
cortex male male 2w v male 1w               0          0
cortex male male 4w v male 2w               2          6
cortex male male 8w v male 4w               6          2

**Time Point Versus 0 Comparisons**

                                     up genes down genes
comparison
cortex male male 1w v male sedentary        0          1
cortex male male 2w v male sedentary        0          0
cortex male male 4w v male sedentary        2          9
cortex male male 8w v male sedentary        0          0

**Adjacent Time Point Comparisons**

                                           up genes down genes
comparison
cortex female female 1w v female sedentary        1         13
cortex female female 2w v female 1w               1          0
cortex female female 4w v female 2w               0          1
cortex female female 8w v female 4w               0          1

**Time Point Versus 0 Comparisons**

                                           up genes down genes
comparison
cortex female female 1w v female sedentary        1         13
cortex female female 2w v female sedentary       15         11
cortex female female 4w v female sedentary        1          2
cortex female female 8w v female sedentary        0          1

**Adjacent Time Point Comparisons**

                                               up genes down genes
comparison
vastus-lateralis male male 1w v male sedentary       20          5
vastus-lateralis male male 2w v male 1w               0          0
vastus-lateralis male male 4w v male 2w               0          0
vastus-lateralis male male 8w v male 4w              20         37

**Time Point Versus 0 Comparisons**

                                               up genes down genes
comparison
vastus-lateralis male male 1w v male sedentary       20          5
vastus-lateralis male male 2w v male sedentary        9         10
vastus-lateralis male male 4w v male sedentary       32         23
vastus-lateralis male male 8w v male sedentary       94        248

**Adjacent Time Point Comparisons**

                                                   up genes down genes
comparison
vastus-lateralis female female 1w v female sede...       12         18
vastus-lateralis female female 2w v female 1w             2          1
vastus-lateralis female female 4w v female 2w            30        193
vastus-lateralis female female 8w v female 4w            29         15

**Time Point Versus 0 Comparisons**

                                                   up genes down genes
comparison
vastus-lateralis female female 1w v female sede...       12         18
vastus-lateralis female female 2w v female sede...       39         53
vastus-lateralis female female 4w v female sede...      291        203
vastus-lateralis female female 8w v female sede...      194        109

**Adjacent Time Point Comparisons**

                                   up genes down genes
comparison
lung male male 1w v male sedentary       74         45
lung male male 2w v male 1w               0          0
lung male male 4w v male 2w              70         36
lung male male 8w v male 4w             148        208

**Time Point Versus 0 Comparisons**

                                   up genes down genes
comparison
lung male male 1w v male sedentary       74         45
lung male male 2w v male sedentary       13         10
lung male male 4w v male sedentary       94         69
lung male male 8w v male sedentary       69         92

**Adjacent Time Point Comparisons**

                                         up genes down genes
comparison
lung female female 1w v female sedentary      343        789
lung female female 2w v female 1w              29         76
lung female female 4w v female 2w              66         16
lung female female 8w v female 4w             101         93

**Time Point Versus 0 Comparisons**

                                         up genes down genes
comparison
lung female female 1w v female sedentary      343        789
lung female female 2w v female sedentary      612       1013
lung female female 4w v female sedentary      243        502
lung female female 8w v female sedentary        4          7

**Adjacent Time Point Comparisons**

                                    up genes down genes
comparison
heart male male 1w v male sedentary       81         20
heart male male 2w v male 1w               3          8
heart male male 4w v male 2w               0          4
heart male male 8w v male 4w              71        112

**Time Point Versus 0 Comparisons**

                                    up genes down genes
comparison
heart male male 1w v male sedentary       81         20
heart male male 2w v male sedentary      184         57
heart male male 4w v male sedentary      133         49
heart male male 8w v male sedentary      278        225

**Adjacent Time Point Comparisons**

                                          up genes down genes
comparison
heart female female 1w v female sedentary        7          5
heart female female 2w v female 1w               0          1
heart female female 4w v female 2w               0          3
heart female female 8w v female 4w               0          3

**Time Point Versus 0 Comparisons**

                                          up genes down genes
comparison
heart female female 1w v female sedentary        7          5
heart female female 2w v female sedentary       74         49
heart female female 4w v female sedentary       42         12
heart female female 8w v female sedentary       94         47

**Adjacent Time Point Comparisons**

                                     up genes down genes
comparison
kidney male male 1w v male sedentary        3          7
kidney male male 2w v male 1w               0          0
kidney male male 4w v male 2w               0          1
kidney male male 8w v male 4w              12          6

**Time Point Versus 0 Comparisons**

                                     up genes down genes
comparison
kidney male male 1w v male sedentary        3          7
kidney male male 2w v male sedentary        2          5
kidney male male 4w v male sedentary        2         16
kidney male male 8w v male sedentary      125        238

**Adjacent Time Point Comparisons**

                                           up genes down genes
comparison
kidney female female 1w v female sedentary       81        124
kidney female female 2w v female 1w               0          0
kidney female female 4w v female 2w              22         25
kidney female female 8w v female 4w               3          0

**Time Point Versus 0 Comparisons**

                                           up genes down genes
comparison
kidney female female 1w v female sedentary       81        124
kidney female female 2w v female sedentary       48         59
kidney female female 4w v female sedentary        0          0
kidney female female 8w v female sedentary        8          4

**Adjacent Time Point Comparisons**

                                              up genes down genes
comparison
small-intestine male male 1w v male sedentary        1          5
small-intestine male male 2w v male 1w               0          0
small-intestine male male 4w v male 2w               0          2
small-intestine male male 8w v male 4w              19          4

**Time Point Versus 0 Comparisons**

                                              up genes down genes
comparison
small-intestine male male 1w v male sedentary        1          5
small-intestine male male 2w v male sedentary        3          6
small-intestine male male 4w v male sedentary        2          9
small-intestine male male 8w v male sedentary        0          1

**Adjacent Time Point Comparisons**

                                                   up genes down genes
comparison
small-intestine female female 1w v female seden...      105         77
small-intestine female female 2w v female 1w              5          5
small-intestine female female 4w v female 2w             83        132
small-intestine female female 8w v female 4w             29         15

**Time Point Versus 0 Comparisons**

                                                   up genes down genes
comparison
small-intestine female female 1w v female seden...      105         77
small-intestine female female 2w v female seden...       14         31
small-intestine female female 4w v female seden...      126         51
small-intestine female female 8w v female seden...        0          0

**Adjacent Time Point Comparisons**

                                     up genes down genes
comparison
spleen male male 1w v male sedentary        1          0
spleen male male 2w v male 1w              11          1
spleen male male 4w v male 2w              36        319
spleen male male 8w v male 4w             415        368

**Time Point Versus 0 Comparisons**

                                     up genes down genes
comparison
spleen male male 1w v male sedentary        1          0
spleen male male 2w v male sedentary       44         22
spleen male male 4w v male sedentary       42          7
spleen male male 8w v male sedentary      575        653

**Adjacent Time Point Comparisons**

                                           up genes down genes
comparison
spleen female female 1w v female sedentary       30         25
spleen female female 2w v female 1w               3          0
spleen female female 4w v female 2w              11          7
spleen female female 8w v female 4w             551        205

**Time Point Versus 0 Comparisons**

                                           up genes down genes
comparison
spleen female female 1w v female sedentary       30         25
spleen female female 2w v female sedentary       27         50
spleen female female 4w v female sedentary       35         30
spleen female female 8w v female sedentary       12          1

**Adjacent Time Point Comparisons**

                                    up genes down genes
comparison
colon male male 1w v male sedentary      135        140
colon male male 2w v male 1w               1          0
colon male male 4w v male 2w              27         56
colon male male 8w v male 4w               9          7

**Time Point Versus 0 Comparisons**

                                    up genes down genes
comparison
colon male male 1w v male sedentary      135        140
colon male male 2w v male sedentary       30          8
colon male male 4w v male sedentary        3         13
colon male male 8w v male sedentary        8          8

**Adjacent Time Point Comparisons**

                                          up genes down genes
comparison
colon female female 1w v female sedentary       28         41
colon female female 2w v female 1w               0          0
colon female female 4w v female 2w               2          3
colon female female 8w v female 4w               6          8

**Time Point Versus 0 Comparisons**

                                          up genes down genes
comparison
colon female female 1w v female sedentary       28         41
colon female female 2w v female sedentary       49        131
colon female female 4w v female sedentary        1          0
colon female female 8w v female sedentary        0          1

**Adjacent Time Point Comparisons**

                                        up genes down genes
comparison
vena-cava male male 4w v male sedentary       14          1
vena-cava male male 8w v male 4w               1          9

**Time Point Versus 0 Comparisons**

                                        up genes down genes
comparison
vena-cava male male 4w v male sedentary       14          1
vena-cava male male 8w v male sedentary        0          0

**Adjacent Time Point Comparisons**

                                              up genes down genes
comparison
vena-cava female female 4w v female sedentary       36         21
vena-cava female female 8w v female 4w               0          0

**Time Point Versus 0 Comparisons**

                                              up genes down genes
comparison
vena-cava female female 4w v female sedentary       36         21
vena-cava female female 8w v female sedentary        0          0

**Adjacent Time Point Comparisons**

                                           up genes down genes
comparison
hypothalamus male male 1w v male sedentary        0          0
hypothalamus male male 2w v male 1w               1          0
hypothalamus male male 4w v male 2w               0          0
hypothalamus male male 8w v male 4w             170        128

**Time Point Versus 0 Comparisons**

                                           up genes down genes
comparison
hypothalamus male male 1w v male sedentary        0          0
hypothalamus male male 2w v male sedentary       92         53
hypothalamus male male 4w v male sedentary       21         29
hypothalamus male male 8w v male sedentary        0          0

**Adjacent Time Point Comparisons**

                                                 up genes down genes
comparison
hypothalamus female female 1w v female sedentary       14         13
hypothalamus female female 2w v female 1w               1          1
hypothalamus female female 4w v female 2w               0          1
hypothalamus female female 8w v female 4w               0          0

**Time Point Versus 0 Comparisons**

                                                 up genes down genes
comparison
hypothalamus female female 1w v female sedentary       14         13
hypothalamus female female 2w v female sedentary      161         69
hypothalamus female female 4w v female sedentary        0          1
hypothalamus female female 8w v female sedentary        0          0

**Adjacent Time Point Comparisons**

                                          up genes down genes
comparison
hippocampus male male 1w v male sedentary       90         39
hippocampus male male 2w v male 1w               7          7
hippocampus male male 4w v male 2w               0          0
hippocampus male male 8w v male 4w               9          6

**Time Point Versus 0 Comparisons**

                                          up genes down genes
comparison
hippocampus male male 1w v male sedentary       90         39
hippocampus male male 2w v male sedentary       16          7
hippocampus male male 4w v male sedentary        1          5
hippocampus male male 8w v male sedentary       22         37

**Adjacent Time Point Comparisons**

                                                up genes down genes
comparison
hippocampus female female 1w v female sedentary        1         19
hippocampus female female 2w v female 1w               0          1
hippocampus female female 4w v female 2w               0          0
hippocampus female female 8w v female 4w               0          0

**Time Point Versus 0 Comparisons**

                                                up genes down genes
comparison
hippocampus female female 1w v female sedentary        1         19
hippocampus female female 2w v female sedentary        1          2
hippocampus female female 4w v female sedentary        0          0
hippocampus female female 8w v female sedentary        0          0

**Adjacent Time Point Comparisons**

                                            up genes down genes
comparison
brown-adipose male male 1w v male sedentary        0          1
brown-adipose male male 2w v male 1w              13          3
brown-adipose male male 4w v male 2w              28        103
brown-adipose male male 8w v male 4w             787        574

**Time Point Versus 0 Comparisons**

                                            up genes down genes
comparison
brown-adipose male male 1w v male sedentary        0          1
brown-adipose male male 2w v male sedentary       13          3
brown-adipose male male 4w v male sedentary        1          0
brown-adipose male male 8w v male sedentary      835        464

**Adjacent Time Point Comparisons**

                                                  up genes down genes
comparison
brown-adipose female female 1w v female sedentary       16         88
brown-adipose female female 2w v female 1w               0          1
brown-adipose female female 4w v female 2w              17         34
brown-adipose female female 8w v female 4w             551        420

**Time Point Versus 0 Comparisons**

                                                  up genes down genes
comparison
brown-adipose female female 1w v female sedentary       16         88
brown-adipose female female 2w v female sedentary       21        197
brown-adipose female female 4w v female sedentary        8        217
brown-adipose female female 8w v female sedentary        5          0

**Adjacent Time Point Comparisons**

                                            up genes down genes
comparison
white-adipose male male 1w v male sedentary      112         55
white-adipose male male 2w v male 1w               0          0
white-adipose male male 4w v male 2w              18         70
white-adipose male male 8w v male 4w               8          5

**Time Point Versus 0 Comparisons**

                                            up genes down genes
comparison
white-adipose male male 1w v male sedentary      112         55
white-adipose male male 2w v male sedentary     1215        689
white-adipose male male 4w v male sedentary       14          6
white-adipose male male 8w v male sedentary      224         90

**Adjacent Time Point Comparisons**

                                                  up genes down genes
comparison
white-adipose female female 1w v female sedentary        7         18
white-adipose female female 2w v female 1w               0          0
white-adipose female female 4w v female 2w              60         43
white-adipose female female 8w v female 4w              14          9

**Time Point Versus 0 Comparisons**

                                                  up genes down genes
comparison
white-adipose female female 1w v female sedentary        7         18
white-adipose female female 2w v female sedentary       24         12
white-adipose female female 4w v female sedentary       18          7
white-adipose female female 8w v female sedentary      245         51

**Adjacent Time Point Comparisons**

                                      up genes down genes
comparison
adrenal male male 1w v male sedentary     1119        315
adrenal male male 2w v male 1w              42         25
adrenal male male 4w v male 2w             200        178
adrenal male male 8w v male 4w             160        357

**Time Point Versus 0 Comparisons**

                                      up genes down genes
comparison
adrenal male male 1w v male sedentary     1119        315
adrenal male male 2w v male sedentary      269         72
adrenal male male 4w v male sedentary       24         14
adrenal male male 8w v male sedentary      112        181

**Adjacent Time Point Comparisons**

                                            up genes down genes
comparison
adrenal female female 1w v female sedentary        5          0
adrenal female female 2w v female 1w               2          1
adrenal female female 4w v female 2w              13          8
adrenal female female 8w v female 4w              58        236

**Time Point Versus 0 Comparisons**

                                            up genes down genes
comparison
adrenal female female 1w v female sedentary        5          0
adrenal female female 2w v female sedentary      169         64
adrenal female female 4w v female sedentary        4          0
adrenal female female 8w v female sedentary      494        964

**Adjacent Time Point Comparisons**

                                    up genes down genes
comparison
liver male male 1w v male sedentary        7          2
liver male male 2w v male 1w               3          3
liver male male 4w v male 2w               5          1
liver male male 8w v male 4w              54         34

**Time Point Versus 0 Comparisons**

                                    up genes down genes
comparison
liver male male 1w v male sedentary        7          2
liver male male 2w v male sedentary       22         13
liver male male 4w v male sedentary       78         25
liver male male 8w v male sedentary      141         93

**Adjacent Time Point Comparisons**

                                          up genes down genes
comparison
liver female female 1w v female sedentary       77         86
liver female female 2w v female 1w               0          0
liver female female 4w v female 2w              83        119
liver female female 8w v female 4w              34         28

**Time Point Versus 0 Comparisons**

                                          up genes down genes
comparison
liver female female 1w v female sedentary       77         86
liver female female 2w v female sedentary       29         19
liver female female 4w v female sedentary        6          2
liver female female 8w v female sedentary       50         33

**Adjacent Time Point Comparisons**

                                            up genes down genes
comparison
gastrocnemius male male 1w v male sedentary      127         68
gastrocnemius male male 2w v male 1w              11         20
gastrocnemius male male 4w v male 2w               0          0
gastrocnemius male male 8w v male 4w              15         17

**Time Point Versus 0 Comparisons**

                                            up genes down genes
comparison
gastrocnemius male male 1w v male sedentary      127         68
gastrocnemius male male 2w v male sedentary       55         53
gastrocnemius male male 4w v male sedentary       45         37
gastrocnemius male male 8w v male sedentary      239        294

**Adjacent Time Point Comparisons**

                                                  up genes down genes
comparison
gastrocnemius female female 1w v female sedentary       82        121
gastrocnemius female female 2w v female 1w              10         10
gastrocnemius female female 4w v female 2w               6         13
gastrocnemius female female 8w v female 4w               3          2

**Time Point Versus 0 Comparisons**

                                                  up genes down genes
comparison
gastrocnemius female female 1w v female sedentary       82        121
gastrocnemius female female 2w v female sedentary       24         29
gastrocnemius female female 4w v female sedentary       39         24
gastrocnemius female female 8w v female sedentary       17         39